name: Terraform Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Terratest
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Init Go module
      run: |
        go mod init terraform-infra || true
        go get github.com/gruntwork-io/terratest/modules/terraform
        go mod tidy

    - name: Run Terratest
      run: go test -v ./envs/dev/test
 
